In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
np.save('abc.npy',a)

In [4]:
b = np.load('abc.npy')

In [5]:
type(b)

numpy.ndarray

In [6]:
import scipy.spatial.distance

In [7]:
a = np.array([[1 , 2 , 3], 
             [4 , 5,  6]])

In [8]:
b = np.array([[7 , 8 , 9], 
             [10 , 11,  12]])

In [9]:
scipy.spatial.distance.cdist(np.transpose(a), np.transpose(b))

array([[ 8.48528137,  9.89949494, 11.3137085 ],
       [ 7.07106781,  8.48528137,  9.89949494],
       [ 5.65685425,  7.07106781,  8.48528137]])

In [10]:
a.shape

(2, 3)

In [11]:
def sub(a):
    return a - a

In [12]:
def add (n, b, c):
    c = sub(n)
    print(c)
    return [n * n + b , c]

In [13]:
import multiprocessing
listab = [1 , 2, 3]

In [14]:
from joblib import Parallel, delayed
c = np.ones((2,2))
d = 1
return_values = Parallel(n_jobs=6)(delayed(add)(input , d, c) for input in listab)
print(np.array(return_values)[:,1])

[0 0 0]


In [15]:
from multiprocessing import set_start_method
set_start_method("spawn")

RuntimeError: context has already been set

In [ ]:
with multiprocessing.Pool(8) as p:
        print("threads")
        p.map(add, list)
        p.close() # <-- calling close before P.join()
        p.join()

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2, 3], [1, 4, -1], [1, 0, 4], [10, 2, 10], [10, 4, 7], [10, 0, 2]])
print(X.shape)
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.cluster_centers_

In [ ]:
Xin = np.random.randint(10,size = (4, 3, 3))
#Xal = np.reshape(Xin, (4,2))
Xal = Xin.reshape(3,-1)

print(Xin)
print(Xal)
#print(Xal)

In [ ]:
Yin = np.random.randint(10,size = (2, 2))
Yin

In [ ]:
dist = scipy.spatial.distance.cdist(Xin, Yin)

In [ ]:
a = [1, 2, 3, 4, 5]
d = [6, 7, 8, 9, 10]

In [ ]:
c = []
c.append(a)
c.append(d)

In [ ]:
b = np.concatenate(c, axis = 0)
b

In [ ]:
b[:-1]

In [ ]:
b[:, -1]

In [ ]:
weights = np.zeros((3,1))

In [ ]:
L = 2

In [ ]:
weights = np.zeros((L+1,1))
for i in range(L+1):
    if i == 0 or i == 1:
        weights[i] = 2**(-L)
    else:
        weights[i] = 2**(i-L-1)
weights

In [ ]:
import math

In [ ]:
w = 309
h = 500
L = 3
indices_w = []
indices_h = []
count_x = []
for i in range(L + 1):
    i_w = [0]
    i_h = [0]
    count = []
    patch_width = math.floor(w / (2**(i)))
    patch_height = math.floor(h / (2**(i)))
    for j in range(2**(i)):
        i_w.append((j + 1) * patch_width)
        i_h.append((j + 1) * patch_height)
    for j in range(2**(i)):
        count.append(j)
    count_x.append(count)
    indices_w.append(i_w)
    indices_h.append(i_h)
for i in range(L + 1):
    for j in range(2**(i)):
        for k in range(2**(i)):
            print(indices_h[i][j], indices_h[i][j + 1])
            print(indices_w[i][k], indices_w[i][k + 1])
    print("\n")

In [ ]:
print(indices_w)
print(indices_w[1][2])
print(indices_h)
print(count_x)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.tile(a, (5,1))

In [ ]:
b

In [ ]:
c = np.sum(b)

In [ ]:
c = np.trace(b)

In [ ]:
a = np.argmin(np.array([1, 2, 3, 4, 0]))
a

In [ ]:
c

In [ ]:
conf_matrix = np.zeros((8, 8))

In [ ]:
conf_matrix

In [ ]:
def get_feature_from_wordmap_SPM(wordmap, layer_num, dict_size):
    '''
    Compute histogram of visual words using spatial pyramid matching.

    [input]
    * wordmap: numpy.ndarray of shape (H,W)
    * layer_num: number of spatial pyramid layers
    * dict_size: dictionary size K

    [output]
    * hist_all: numpy.ndarray of shape (K*(4^layer_num-1)/3)
    '''
    '''
    HINTS:
    (1) Take care of Weights 
    (2) Try to build the pyramid in Bottom Up Manner
    (3) the output array should first contain the histogram for Level 0 (top most level) , followed by Level 1, and then Level 2.
    '''
    # ----- TODO -----
    h, w = wordmap.shape
    L = layer_num - 1
    patch_width = math.floor(w / (2**L))
    patch_height = math.floor(h / (2**L))
    
    '''
    HINTS:
    1.> create an array of size (dict_size, (4**(L + 1) -1)/3) )
    2.> pre-compute the starts, ends and weights for the SPM layers L
    '''
            
    # YOUR CODE HERE
    hist_all = np.zeros((dict_size, int(((4**(L + 1) -1))/3)))
    weights = np.zeros((L+1,1))
    for i in range(L + 1):
        if i == 0 or i == 1:
            weights[i] = 2**(-L)
        else:
            weights[i] = 2**(i-L-1)
    
    indices_w = []
    indices_h = []
    for i in range(L + 1):
        i_w = [0]
        i_h = [0]
        patch_width = math.floor(w / (2**(i)))
        patch_height = math.floor(h / (2**(i)))
        for j in range(2**(i)):
            i_w.append((j + 1) * patch_width)
            i_h.append((j + 1) * patch_height)
        indices_w.append(i_w)
        indices_h.append(i_h)

            
    # raise NotImplementedError()
    '''
    HINTS:
    1.> Loop over the layers from L to 0
    2.> Handle the base case (Layer L) separately and then build over that
    3.> Normalize each histogram separately and also normalize the final histogram
    '''
    # YOUR CODE HERE
    hist_all_f = []
    for i in range(L + 1):
        hist_all_temp = []
        for j in range(2**(i)):
            for k in range(2**(i)):
                histo = get_feature_from_wordmap(wordmap[indices_h[i][j]:indices_h[i][j + 1] , indices_w[i][k]:indices_w[i][k + 1]], dict_size)
                hist_all_temp.append(get_feature_from_wordmap(wordmap[indices_h[i][j]:indices_h[i][j + 1] , indices_w[i][k]:indices_w[i][k + 1]], dict_size))
                plt.figure()
                bin_edges = np.arange(dict_size + 1)
                plt.bar(bin_edges[:-1], histo, width = 1)
                plt.xlim(0, 200)
                plt.show() 
        hist_all_f.append(hist_all_temp)
    for i in range(L + 1):
        hist_all_f[i] = hist_all_f[i] * weights[i] * (1 / (2**(i) * 2**(i)))
    
    hist_all = np.concatenate(hist_all_f, axis=0)
    hist_all = np.transpose(hist_all).flatten()
        
    # raise NotImplementedError()
    return hist_all


In [ ]:
L = 2
for l in range(L, -1, -1):
    print(l)

In [ ]:
def get_feature_from_wordmap_SPM(wordmap, layer_num, dict_size):
    '''
    Compute histogram of visual words using spatial pyramid matching.

    [input]
    * wordmap: numpy.ndarray of shape (H,W)
    * layer_num: number of spatial pyramid layers
    * dict_size: dictionary size K

    [output]
    * hist_all: numpy.ndarray of shape (K*(4^layer_num-1)/3)
    '''
    '''
    HINTS:
    (1) Take care of Weights 
    (2) Try to build the pyramid in Bottom Up Manner
    (3) the output array should first contain the histogram for Level 0 (top most level) , followed by Level 1, and then Level 2.
    '''
    # ----- TODO -----
    h, w = wordmap.shape
    L = layer_num - 1
    n_rows_L = 2**L
    n_cols_L = 2**L
    patch_width = math.floor(w / (2**L))
    patch_height = math.floor(h / (2**L))

    '''
    HINTS:
    1.> create an array of size (dict_size, (4**(L + 1) -1)/3) )
    2.> pre-compute the starts, ends and weights for the SPM layers L 
    '''
    weights = np.zeros((L+1,1))
    for i in range(L + 1):
        if i == 0 or i == 1:
            weights[i] = 2**(-L)
        else:
            weights[i] = 2**(i-L-1)
    # YOUR CODE HERE
    #raise NotImplementedError()
    '''
    HINTS:
    1.> Loop over the layers from L to 0
    2.> Handle the base case (Layer L) separately and then build over that
    3.> Normalize each histogram separately and also normalize the final histogram
    '''
    print(dict_size) 
    output = []
    for x in range(L):
        y = (L) - x
        output_new=[]
        hist_new=[]
        n_col = 2**y
        n_row = 2**y
        patch_w = math.floor(w / (2**y))
        patch_h = math.floor(h / (2**y)) 
        stride = int(n_cols_L/n_col) 
        if y == L:
            hist_all_L = np.zeros((n_rows_L, n_cols_L, dict_size))
            for i in range(n_rows_L):
                for j in range(n_cols_L):
                    word_patch = wordmap[i*patch_h: (i+1)*patch_h, j*patch_w : (j+1)*patch_w ]
                    hist = get_feature_from_wordmap(word_patch,dict_size)
                    hist_all_L[i,j,:] = hist
                    output= np.hstack([output, hist*weights[y]])

        else:            
            for i in range(n_row):
                for j in range(n_col):
                    hist_new = np.concatenate((hist_all_L[stride*i:stride*(i+1),stride*j:stride*(j+1),: ]))
                    hist_new = np.sum(hist_new, axis = 0)
                    #print("flag histnew: ", hist_new.shape)
                    hist_new = np.reshape(hist_new,(-1))
                    #hist_new = hist_new.flatten()
                    #print("flag 1: ", hist_new.shape)
                    output_new= np.hstack([output_new, hist_new*weights[y]])
                    #print("flag 3 :", output_new.shape)
            #print("flag 4 :", output_new.shape)
        output= np.hstack([output_new, output])
        #print("flag 5 :", output.shape)
    
    hist_all = output
    hist_all = hist_all/np.sum(hist_all)
    
    return hist_all


In [ ]:
import multiprocessing

In [16]:
def add(a, b):
    print(a + b)

In [ ]:
with multiprocessing.Pool(4) as p:
    #    print("threads")
    p.map(add, [6, 7 , 8 , 9 ,10])

In [18]:
a = 2* np.ones((3, 3, 3))
b = np.ones((3, 3))
import scipy.ndimage
L = scipy.ndimage.convolve(a, b, mode = "constant")
M = np.sum(L, axis = 2)
print(M)

RuntimeError: filter weights array has incorrect shape.

In [28]:
a = np.ones((5,5))
c = np.maximum(a, 0)
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
a = np.array([[1., 2., 3., 4., 5.],
 [6., 7., 8., 9., 10.],
 [11., 12., 13., 14., 15.],
 [16., 17., 18., 19., 10.],
 [21., 22., 23., 24., 25.]])
b = np.array([[2,1],[3,4]])
print(b.shape)
print(a[b])

(2, 2)
[[[11. 12. 13. 14. 15.]
  [ 6.  7.  8.  9. 10.]]

 [[16. 17. 18. 19. 10.]
  [21. 22. 23. 24. 25.]]]


In [38]:
a = np.ones((6,5))
b = np.array([1, 2, 3, 4, 5])
print(a @ b)

[15. 15. 15. 15. 15. 15.]


In [39]:
mean = np.array([0.485,0.456,0.406])
std = np.array([0.229,0.224,0.225])

In [40]:
mean.shape

(3,)

In [41]:
M = np.tile(mean, (3,3,1))

In [45]:
M[:,:,2]

array([[0.406, 0.406, 0.406],
       [0.406, 0.406, 0.406],
       [0.406, 0.406, 0.406]])

In [56]:
S = np.tile(std, (4,4,1))

In [49]:
np.divide(M, S)

array([[[2.11790393, 2.03571429, 1.80444444],
        [2.11790393, 2.03571429, 1.80444444],
        [2.11790393, 2.03571429, 1.80444444]],

       [[2.11790393, 2.03571429, 1.80444444],
        [2.11790393, 2.03571429, 1.80444444],
        [2.11790393, 2.03571429, 1.80444444]],

       [[2.11790393, 2.03571429, 1.80444444],
        [2.11790393, 2.03571429, 1.80444444],
        [2.11790393, 2.03571429, 1.80444444]]])

In [50]:
M

array([[[0.485, 0.456, 0.406],
        [0.485, 0.456, 0.406],
        [0.485, 0.456, 0.406]],

       [[0.485, 0.456, 0.406],
        [0.485, 0.456, 0.406],
        [0.485, 0.456, 0.406]],

       [[0.485, 0.456, 0.406],
        [0.485, 0.456, 0.406],
        [0.485, 0.456, 0.406]]])

In [51]:
M.shape

(3, 3, 3)

In [52]:
import torch

In [58]:
Ctr = torch.from_numpy(S)
Ctr.size()

torch.Size([4, 4, 3])

In [59]:
A = [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [60]:
len(A)

5

In [61]:
for x in range(7):
    print(x)

0
1
2
3
4
5
6


In [2]:
N = [1,2,3,4,5]
N[:-3]

[1, 2]

In [4]:
import numpy as np

In [13]:
c = np.array([1, 2, 3, 4, 5])
b = np.array([[10., 20., 30., 40., 50.],
 [6., 7., 8., 9., 10.],
 [11., 12., 13., 14., 15.],
 [16., 17., 18., 19., 10.],
 [21., 22., 23., 24., 25.]])
dist_test = np.tile(c, (b.shape[0], 1))
print(dist_test)
distances = np.sum((dist_test - b)**2, axis = 1)
print(distances)
nearest_image_idx = np.argmin(distances)
print(nearest_image_idx)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[4455.  125.  500.  925. 2000.]
1


In [47]:
A  = np.array([[[1, 2, 3, 4], [4, 5 , 6, 21], [7, 8, 9, 2], [1 , 3, 55, 6]], [[1, 2, 3, 4], [4, 5 , 6, 21], [7, 8, 9, 2], [1 , 3, 55, 6]], [[1, 2, 3, 4], [4, 5 , 6, 21], [7, 8, 9, 2], [1 , 3, 55, 6]]])
print(A.shape)
B = np.transpose(A, (2, 0, 1))
C = A.flatten()
print(C)
D = B.flatten()
print(D)
E = D.reshape((3,3,3))

(3, 4, 4)
[ 1  2  3  4  4  5  6 21  7  8  9  2  1  3 55  6  1  2  3  4  4  5  6 21
  7  8  9  2  1  3 55  6  1  2  3  4  4  5  6 21  7  8  9  2  1  3 55  6]
[ 1  4  7  1  1  4  7  1  1  4  7  1  2  5  8  3  2  5  8  3  2  5  8  3
  3  6  9 55  3  6  9 55  3  6  9 55  4 21  2  6  4 21  2  6  4 21  2  6]


ValueError: cannot reshape array of size 48 into shape (3,3,3)

In [21]:
a = np.array([0, 1, 2])
c = np.tile(a, (2, 1, 2))
print(c.shape)

(2, 1, 6)


In [31]:
print(np.transpose(E, (1, 2, 0)).flatten())

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [ ]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import scipy.ndimage

def pytorch_conv2d(x, w, b):

    x_reorder = np.moveaxis(x, [0, 1, 2], [1, 2, 0])
    x_input = np.expand_dims(x_reorder, axis = 0)

    x_t = torch.from_numpy(x_input)
    w_t = torch.from_numpy(w)

    # print(f"{x_t.shape=}, {w_t.shape=}")

    o_t = F.conv2d(x_t, w_t, padding=1)

    output = o_t.numpy()
    
    output = output[0,:,:,:]

    return output

np.random.seed(0)
x = np.random.rand(10, 10, 2)
w = np.random.rand(4, 2, 3, 3)
b = np.zeros((4))

pyoutput = pytorch_conv2d(x, w, b)
cuoutput = multichannel_conv2d(x,w,b)

cuoutput = np.moveaxis(cuoutput, [0, 1, 2], [1, 2, 0])

diff = pyoutput - cuoutput

print(np.sum(diff.flatten()))

In [42]:
def max_pool2d(x,size):
    '''
    2D max pooling operation.

    [input]
    * x: numpy.ndarray of shape (H,W,input_dim)
    * size: pooling receptive field

    [output]
    * y: numpy.ndarray of shape (H/size,W/size,input_dim)
    '''
    h, w, dims = x.shape
    ind1 = np.floor(h/size).astype(int)
    ind2 = np.floor(w/size).astype(int)
    
    pooled_arr = np.zeros((ind1, ind2, dims))
    '''
    
    HINTS:
    1.> estimate the shape you need to apply the pooling operation.
    2.> We can smart fill the padding with np.nan and then use np.nanmax to select the max (avoiding nan)
    3.> We can input the grid (start_x:end_x, start_y:end_y, dim) as smart array indexing to np.nanmax
    '''
    # YOUR CODE HERE
    for k in range(dims):
        for i in range(ind1):
            for j in range(ind2):
                pooled_arr[i,j, k] = np.max(x[i*size:(i+1)*size, j*size:(j+1)*size, k]) 
                print(x[i*size:(i+1)*size, j*size:(j+1)*size, k])
                
    return pooled_arr

In [65]:
A  = np.array([[[1, 2, 3, 4], [4, 5 , 6, 21], [7, 8, 9, 2], [1 , 3, 55, 6]], [[1, 2, 3, 4], [4, 5 , 6, 21], [7, 8, 9, 2], [1 , 3, 55, 6]], [[1, 2, 3, 4], [4, 5 , 6, 21], [7, 8, 9, 2], [1 , 3, 55, 66]]])


In [66]:
B = np.transpose(A, (1, 2, 0))
C = max_pool2d(B, 2)

[[1 2]
 [4 5]]
[[ 3  4]
 [ 6 21]]
[[7 8]
 [1 3]]
[[ 9  2]
 [55  6]]
[[1 2]
 [4 5]]
[[ 3  4]
 [ 6 21]]
[[7 8]
 [1 3]]
[[ 9  2]
 [55  6]]
[[1 2]
 [4 5]]
[[ 3  4]
 [ 6 21]]
[[7 8]
 [1 3]]
[[ 9  2]
 [55 66]]


In [67]:
print(C.shape)
print(B[:, :, 2])
print(B.shape)
print(A.shape)

(2, 2, 3)
[[ 1  2  3  4]
 [ 4  5  6 21]
 [ 7  8  9  2]
 [ 1  3 55 66]]
(4, 4, 3)
(3, 4, 4)


In [68]:
print(C[:, :, 2])

[[ 5. 21.]
 [ 8. 66.]]


In [69]:
def relu(x):
    '''
    Rectified linear unit.

    [input]
    * x: numpy.ndarray

    [output]
    * y: numpy.ndarray
    '''
    # YOUR CODE HERE
    y = np.maximum(x, 0)
    # raise NotImplementedError()
    return y

In [70]:
print(relu(np.array([-1, -1 ,3, 4, 5])))

[0 0 3 4 5]


In [2]:
def save_wordmap(wordmap):
    fig = plt.figure(2)
    plt.axis('equal')
    plt.axis('off')
    plt.imshow(wordmap, cmap="rainbow")
    # plt.savefig(filename, pad_inches=0)
    
dictionary = np.load('./dictionary.npy')

path_img = "./data/kitchen/sun_aggjlwcdjsjcaemh.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

path_img = "./data/aquarium/sun_ayoehnnyhnartpwz.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

path_img = "./data/highway/sun_bebjsikreyhhhefp.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

path_img = "./data/highway/sun_akihkricraebyttv.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

path_img = "./data/highway/sun_aikloxuincjpmnby.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

NameError: name 'np' is not defined

In [3]:
path_img = "./data/laundromat/sun_afrmdtnsnxzodzwq.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

path_img = "./data/highway/sun_agfcebcyjimgbcvr.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

path_img = "./data/laundromat/sun_addinpsdbmiewyvc.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)

path_img = "./data/highway/sun_bsqoowlelpxyjkyt.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)


NameError: name 'io' is not defined

In [4]:
path_img = "./data/kitchen/sun_aggjlwcdjsjcaemh.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)
histo = get_feature_from_wordmap(wordmap, dict_size = 200)
plt.figure()
bin_edges = np.arange(200 + 1)
plt.bar(bin_edges[:-1], histo, width = 1)
plt.xlabel("Words in Dictionary (indices)")
plt.ylabel("Frequency")
plt.xlim(0, 200)
plt.show()

path_img = "./data/aquarium/sun_ayoehnnyhnartpwz.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)
histo = get_feature_from_wordmap(wordmap, dict_size = 200)
plt.figure()
bin_edges = np.arange(200 + 1)
plt.bar(bin_edges[:-1], histo, width = 1)
plt.xlabel("Words in Dictionary (indices)")
plt.ylabel("Frequency")
plt.xlim(0, 200)
plt.show()

path_img = "./data/laundromat/sun_aalvewxltowiudlw.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)
histo = get_feature_from_wordmap(wordmap, dict_size = 200)
plt.figure()
bin_edges = np.arange(200 + 1)
plt.bar(bin_edges[:-1], histo, width = 1)
plt.xlabel("Words in Dictionary (indices)")
plt.ylabel("Frequency")
plt.xlim(0, 200)
plt.show()

path_img = "./data/windmill/sun_avgtzbktnevdkgsy.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)
histo = get_feature_from_wordmap(wordmap, dict_size = 200)
plt.figure()
bin_edges = np.arange(200 + 1)
plt.bar(bin_edges[:-1], histo, width = 1)
plt.xlabel("Words in Dictionary (indices)")
plt.ylabel("Frequency")
plt.xlim(0, 200)
plt.show()

path_img = "./data/highway/sun_aikloxuincjpmnby.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)
histo = get_feature_from_wordmap(wordmap, dict_size = 200)
plt.figure()
bin_edges = np.arange(200 + 1)
plt.bar(bin_edges[:-1], histo, width = 1)
plt.xlabel("Words in Dictionary (indices)")
plt.ylabel("Frequency")
plt.xlim(0, 200)
plt.show()

path_img = "./data/park/labelme_mpjuzxdlazrdgyq.jpg"
#path_img = "./data/aquarium/sun_aztvjgubyrgvirup.jpg"
image = io.imread(path_img)
plt.figure()
plt.axis('equal')
plt.axis('off')
plt.imshow(image)
plt.show()
image = image.astype('float')/255
wordmap = get_visual_words(image, dictionary)
save_wordmap(wordmap)
histo = get_feature_from_wordmap(wordmap, dict_size = 200)
plt.figure()
bin_edges = np.arange(200 + 1)
plt.bar(bin_edges[:-1], histo, width = 1)
plt.xlabel("Words in Dictionary (indices)")
plt.ylabel("Frequency")
plt.xlim(0, 200)
plt.show()

NameError: name 'io' is not defined

In [ ]:
def multichannel_conv2d(x,weight,bias):
    '''
    Performs multi-channel 2D convolution.

    [input]
    * x: numpy.ndarray of shape (H,W,input_dim)
    * weight: numpy.ndarray of shape (output_dim,input_dim,kernel_size,kernel_size)
    * bias: numpy.ndarray of shape (output_dim)

    [output]
    * feat: numpy.ndarray of shape (H,W,output_dim)
    '''
    h, w, input_dims = x.shape
    output_dims = weight.shape[0]
    final_res = np.zeros((h, w, output_dims))
    '''
    HINTS:
    1.> for 2D convolution we need to use np.fliplr and np.flipud
    2.> can use scipy.ndimage.convolve with the flipped kernel
    3.> don't forget to add the bias
    '''
    # YOUR CODE HERE
    inter = np.zeros((h, w, input_dims))
    # filter = np.zeros((weight.shape[2], weight.shape[3]))
    for i in range(output_dims):
        for j in range(input_dims):
            filter = np.fliplr(np.flipud(weight[i,j,:,:]))
            inter[:,:,j] = scipy.ndimage.convolve(x[:,:,j], filter, mode = "constant")
        final_res[:,:,i] = np.sum(inter, axis = 2) + bias[i]    
    # raise NotImplementedError()
    return final_res