In [2]:
import numpy as np

In [5]:
A = np.ones((5, ))
N = 7

In [15]:
Y_max = np.array([np.arange(5), A])

In [16]:
Y_max

array([[0., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1.]])

In [18]:
Y_max.T

array([[0., 1.],
       [1., 1.],
       [2., 1.],
       [3., 1.],
       [4., 1.]])

In [20]:
C = np.random.randint(5, size = (5, 10))

In [21]:
C

array([[2, 0, 2, 2, 4, 4, 4, 0, 3, 2],
       [3, 1, 1, 4, 3, 2, 0, 0, 2, 0],
       [0, 2, 1, 4, 2, 1, 2, 2, 4, 3],
       [0, 0, 3, 2, 2, 3, 4, 2, 1, 3],
       [2, 2, 1, 2, 1, 3, 0, 0, 3, 1]])

In [24]:
C.shape

(5, 10)

In [29]:
Y_max.T[:,0]

array([0., 1., 2., 3., 4.])

In [32]:
C[(Y_max.T[:,0]).astype(int), (Y_max.T[:,1]).astype(int)]

array([0, 1, 2, 0, 2])

In [34]:
D = np.equal(C,C)
D[2,2] = False

In [35]:
D

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [37]:
np.all(D, axis = 1).astype(int)

array([1, 1, 0, 1, 1])

In [41]:
np.argmax(C, axis = 1)

array([4, 3, 3, 6, 5], dtype=int64)

In [42]:
Y_max = np.array([np.arange(5), np.argmax(C, axis = 1)])

In [43]:
Y_max

array([[0, 1, 2, 3, 4],
       [4, 3, 3, 6, 5]], dtype=int64)

In [56]:
ix1 = tuple((Y_max.T[:,0]).astype(int))

In [55]:
ix2 = tuple((Y_max.T[:,1]).astype(int))

In [57]:
C[tuple((Y_max.T[:,0]).astype(int)), tuple((Y_max.T[:,1]).astype(int))] = 1

In [58]:
CC = np.array([[2, 0, 2, 2, 1, 4, 4, 0, 3, 2],
       [3, 1, 1, 1, 3, 2, 0, 0, 2, 0],
       [0, 2, 1, 1, 2, 1, 2, 2, 4, 3],
       [0, 0, 3, 2, 2, 3, 1, 2, 1, 3],
       [2, 2, 1, 2, 1, 1, 0, 0, 3, 1]])

In [59]:
Y_correct = np.all(np.equal(CC,C), axis = 1).astype(int)

In [60]:
acc = np.count_nonzero(Y_correct)/5

In [61]:
acc

1.0

In [63]:
np.sum(CC, axis = 1)

array([20, 13, 18, 17, 13])

In [71]:
d = np.random.randint(0,20, size = 3)

In [69]:
n, c1, c2 = 20, 100, 5
batch_size = 3
x = np.random.rand(n, c1)
y = np.random.rand(n, c2)

In [76]:
x[tuple(d),:].shape

(3, 100)

In [77]:
y_idx = np.array([0 for _ in range(10)] + [1 for _ in range(10)] + [2 for _ in range(10)] + [3 for _ in range(10)])
print(y_idx)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3
 3 3 3]


In [ ]:
if len(v.shape) == 2:
            for i in range(v.shape[0]):
                for j in range(v.shape[1]):
                    #   subtract epsilon
                    params[k][i, j] = v[i, j] - eps
                    #   run the forward function by
                    h1s = forward(x, params, 'layer1')
                    probss = forward(h1s, params, 'output', softmax)
                    #   get the loss
                    ls1, acc1 = compute_loss_and_acc(y , probss)
                    #   add epsilon
                    params[k][i, j] = v[i, j] + eps
                    #   run the forward function
                    h1a = forward(x, params, 'layer1')
                    probsa = forward(h1a, params, 'output', softmax)
                    #   get the loss
                    ls2, acc2 = compute_loss_and_acc(y , probsa)
                    #   compute derivative with central diffs
                    params[k][i, j] = v[i, j]
                    # print((ls2 - ls1))
                    params['grad_' + k][i, j] = (ls2 - ls1) / (2*eps)
        else:
            for i in range(v.shape[0]):
                #   subtract epsilon
                params[k][i] = v[i] - eps
                #   run the forward function by
                h1s = forward(x, params, 'layer1')
                probss = forward(h1s, params, 'output', softmax)
                #   get the loss
                ls1, acc1 = compute_loss_and_acc(y , probss)
                #   add epsilon
                params[k][i] = v[i] + eps
                #   run the forward function
                h1a = forward(x, params, 'layer1')
                probsa = forward(h1a, params, 'output', softmax)
                #   get the loss
                ls2, acc2 = compute_loss_and_acc(y , probsa)
                #   compute derivative with central diffs
                params[k][i] = v[i] 
                params['grad_' + k][i] = (ls2 - ls1) / (2*eps)

In [1]:
import torchvision

In [2]:
torchvision.__version__

'0.8.2+cu101'

In [3]:
import torch

In [4]:
torch.__version__

'1.7.1+cu101'

In [ ]:
class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        
        # Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0,
        #        dilation=1, groups=1, bias=True, padding_mode='zeros')
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        
        # Linear(in_features, out_features, bias=True)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)
        
        # MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False)
        self.max_pool = nn.MaxPool2d(2)
        # ReLU(inplace=False)
        self.relu = nn.ReLU()

    def forward(self, x):
        # Note: the following two ways for max pooling / relu are equivalent.
        # 1) with torch.nn.functional:
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        # 2) with torch.nn:
        x = self.relu(self.max_pool(self.conv2_drop(self.conv2(x))))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

model = ConvNet().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)