In [2]:
import numpy as np

In [3]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
A.shape

(9,)

In [6]:
A.reshape(3,3).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
A = np.array([1, 2, 3])

In [23]:
np.nonzero(A)[0].shape[0]

3

In [15]:
np.any(A == 0)

False

In [26]:
A = np.array([1, 2, 3, 4, 5, 6, 7 ,8 ,9])

In [27]:
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
A = A.reshape(3,3)

In [39]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
A = A.flatten()

In [35]:
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
B = np.argsort(A, axis=1)[:, -1:][:, ::-1]

In [44]:
B

array([[2],
       [2],
       [2]], dtype=int64)

In [45]:
B.shape

(3, 1)

In [46]:
C = np.array([0, 0, 2])

In [47]:
C

array([0, 0, 2])

In [48]:
match_array = np.logical_or.reduce(B == C)

In [49]:
match_array

array([False, False,  True])

In [29]:
window_s = 21
sigma = 5

In [30]:
x, y = np.meshgrid(np.linspace(-1,1,window_s), np.linspace(-1,1,window_s))
dst = np.sqrt(x*x+y*y)
gauss = np.exp(-( (dst)**2 / ( 2.0 * sigma**2 ) ) )

gauss1 = np.flipud(np.fliplr(gauss))
gauss2 = np.fliplr(gauss)
gauss3 = np.flipud(gauss)
gauss4 = gauss

# gauss1 = 
print(gauss)

[[0.96078944 0.96444738 0.96773209 0.97063964 0.97316659 0.97530991
  0.97706705 0.9784359  0.97941483 0.98000265 0.98019867 0.98000265
  0.97941483 0.9784359  0.97706705 0.97530991 0.97316659 0.97063964
  0.96773209 0.96444738 0.96078944]
 [0.96444738 0.96811926 0.97141646 0.97433509 0.97687166 0.97902314
  0.98078697 0.98216103 0.98314368 0.98373375 0.98393051 0.98373375
  0.98314368 0.98216103 0.98078697 0.97902314 0.97687166 0.97433509
  0.97141646 0.96811926 0.96444738]
 [0.96773209 0.97141646 0.9747249  0.97765347 0.98019867 0.98235748
  0.98412732 0.98550606 0.98649206 0.98708414 0.98728157 0.98708414
  0.98649206 0.98550606 0.98412732 0.98235748 0.98019867 0.97765347
  0.9747249  0.97141646 0.96773209]
 [0.97063964 0.97433509 0.97765347 0.98059083 0.98314368 0.98530898
  0.98708414 0.98846702 0.98945598 0.99004983 0.99024786 0.99004983
  0.98945598 0.98846702 0.98708414 0.98530898 0.98314368 0.98059083
  0.97765347 0.97433509 0.97063964]
 [0.97316659 0.97687166 0.98019867 0.983

In [12]:
gauss

array([[0.8824969 , 0.90370708, 0.92311635, 0.94058806, 0.95599748],
       [0.90370708, 0.91197321, 0.92742041, 0.94323195, 0.9577463 ],
       [0.92311635, 0.92742041, 0.93773365, 0.95017299, 0.96252369],
       [0.94058806, 0.94323195, 0.95017299, 0.95941267, 0.96923323],
       [0.95599748, 0.9577463 , 0.96252369, 0.96923323, 0.97669716]])

In [21]:
x, y = np.meshgrid(np.linspace(-1,1,window_s+1), np.linspace(-1,1,window_s+1))
dst = np.sqrt(x*x+y*y)
gauss = np.exp(-( (dst - 0.5)**2 / ( 2.0 * sigma**2 ) ) )
print(gauss.shape)
np.max(gauss)
# gauss1 = 

(11, 11)


0.9999442734627804

In [26]:
import numpy as np
  
# Initializing value of x-axis and y-axis
# in the range -1 to 1
x, y = np.meshgrid(np.linspace(-1,1,21), np.linspace(-1,1,21))
dst = np.sqrt(x*x+y*y)
  
# Intializing sigma and muu
sigma = 1
muu = 0.000
  
# Calculating Gaussian array
gauss = np.exp(-( (dst-muu)**2 / ( 2.0 * sigma**2 ) ) )
  
print("2D Gaussian array :\n")
print(gauss)

2D Gaussian array :

[[0.36787944 0.40454189 0.44043165 0.4747343  0.50661699 0.53526143
  0.55989837 0.57984178 0.59452055 0.60350558 0.60653066 0.60350558
  0.59452055 0.57984178 0.55989837 0.53526143 0.50661699 0.4747343
  0.44043165 0.40454189 0.36787944]
 [0.40454189 0.44485807 0.48432457 0.52204578 0.55710586 0.58860497
  0.6156972  0.63762815 0.65376979 0.66365025 0.66697681 0.66365025
  0.65376979 0.63762815 0.6156972  0.58860497 0.55710586 0.52204578
  0.48432457 0.44485807 0.40454189]
 [0.44043165 0.48432457 0.52729242 0.56836015 0.60653066 0.64082428
  0.67032005 0.69419665 0.71177032 0.72252735 0.72614904 0.72252735
  0.71177032 0.69419665 0.67032005 0.64082428 0.60653066 0.56836015
  0.52729242 0.48432457 0.44043165]
 [0.4747343  0.52204578 0.56836015 0.61262639 0.65376979 0.69073433
  0.72252735 0.74826357 0.76720595 0.77880078 0.78270454 0.77880078
  0.76720595 0.74826357 0.72252735 0.69073433 0.65376979 0.61262639
  0.56836015 0.52204578 0.4747343 ]
 [0.50661699 0.55710

In [23]:
np.max(gauss)

0.9877302162356105

In [24]:
np.argmax(gauss)

44

In [25]:
gauss[44]

IndexError: index 44 is out of bounds for axis 0 with size 10

In [36]:
A = np.ones((3,3))
B = np.ones((3,1))
D = np.ones((1,3))
C = np.concatenate((A.flatten(), B.flatten(), D.flatten()))

In [37]:
C.shape

(15,)

In [38]:
P = np.ones((8,8))

In [40]:
np.expand_dims(P, axis = 0).shape

(1, 8, 8)